// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBft3n3ZmCY9afBX9jZDORtgWLTH3ay3sI',
    appId: '1:802368895523:web:e5b73f0492b156afcacf96',
    messagingSenderId: '802368895523',
    projectId: 'finance-app-1c4a0',
    authDomain: 'finance-app-1c4a0.firebaseapp.com',
    storageBucket: 'finance-app-1c4a0.firebasestorage.app',
    measurementId: 'G-DT21YB2C0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwHLCKzjVwxoCxCaoLuYiEy1Bsacfzxk0',
    appId: '1:802368895523:android:d55d43a93174a346cacf96',
    messagingSenderId: '802368895523',
    projectId: 'finance-app-1c4a0',
    storageBucket: 'finance-app-1c4a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWV83gOjIBmmX52qK39VRzAjg-PitCIs',
    appId: '1:802368895523:ios:d2596f980a440813cacf96',
    messagingSenderId: '802368895523',
    projectId: 'finance-app-1c4a0',
    storageBucket: 'finance-app-1c4a0.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYWV83gOjIBmmX52qK39VRzAjg-PitCIs',
    appId: '1:802368895523:ios:d2596f980a440813cacf96',
    messagingSenderId: '802368895523',
    projectId: 'finance-app-1c4a0',
    storageBucket: 'finance-app-1c4a0.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBft3n3ZmCY9afBX9jZDORtgWLTH3ay3sI',
    appId: '1:802368895523:web:9dba32597752ed91cacf96',
    messagingSenderId: '802368895523',
    projectId: 'finance-app-1c4a0',
    authDomain: 'finance-app-1c4a0.firebaseapp.com',
    storageBucket: 'finance-app-1c4a0.firebasestorage.app',
    measurementId: 'G-D1DLC14TZ2',
  );
}
